"""
Configuration settings for YouTube to MP3 Converter
"""

import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

class Config:
    """Base configuration class."""
    
    # Flask settings
    SECRET_KEY = os.environ.get('SECRET_KEY') or 'dev-secret-key-change-in-production'
    DEBUG = os.environ.get('FLASK_DEBUG', 'False').lower() == 'true'
    
    # Security settings
    SECURITY_PASSWORD_SALT = os.environ.get('SECURITY_PASSWORD_SALT') or 'change-this-salt'
    MAX_CONTENT_LENGTH = 50 * 1024 * 1024  # 50MB max file size
    
    # Directories — use /tmp in production (writable on Render), local dirs in dev
    BASE_DIR = os.path.abspath(os.path.dirname(__file__))
    TEMP_DIR = os.environ.get('TEMP_DIR', os.path.join(BASE_DIR, 'temp'))
    DOWNLOADS_DIR = os.environ.get('DOWNLOADS_DIR', os.path.join(BASE_DIR, 'downloads'))
    
    # YouTube conversion settings
    YOUTUBE_QUALITY_OPTIONS = {
        '128k': '128k',
        '192k': '192k', 
        '320k': '320k'
    }
    
    DEFAULT_QUALITY = '192k'
    
    # FFmpeg settings
    FFmpeg_PATH = os.environ.get('FFMPEG_PATH') or 'ffmpeg'
    FFmpeg_TIMEOUT = 300  # 5 minutes timeout for conversion
    
    # yt-dlp settings
    YTDLP_TIMEOUT = 60  # 1 minute timeout for download
    YTDLP_RETRIES = 3
    
    # Rate limiting settings
    RATELIMIT_STORAGE_URL = 'memory://'
    
    # Security settings
    ALLOWED_EXTENSIONS = {'mp3', 'wav', 'm4a'}
    BLOCKED_HOSTS = {'localhost', '127.0.0.1'}
    
    # CORS settings
    CORS_ORIGINS = os.environ.get('CORS_ORIGINS', 'http://localhost:5000,http://127.0.0.1:5000').split(',')
    
    # Logging settings
    LOG_LEVEL = os.environ.get('LOG_LEVEL', 'INFO')
    LOG_FILE = 'youtube_converter.log'
    
    # Cleanup settings
    CLEANUP_INTERVAL = 3600  # 1 hour in seconds
    FILE_RETENTION_TIME = 3600  # 1 hour in seconds
    
    # User agent for YouTube requests
    USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
    
    # Maximum video duration (in seconds) - 10 hours max
    MAX_VIDEO_DURATION = 36000
    
    # Minimum video duration (in seconds) - 10 seconds min
    MIN_VIDEO_DURATION = 10

class DevelopmentConfig(Config):
    """Development configuration."""
    DEBUG = True
    TESTING = False

class ProductionConfig(Config):
    """Production configuration."""
    DEBUG = False
    TESTING = False

    # More restrictive settings for production
    MAX_CONTENT_LENGTH = 25 * 1024 * 1024  # 25MB max file size

    # Use memory storage on Render free tier (no Redis available)
    RATELIMIT_STORAGE_URL = 'memory://'

    # Writable tmp dirs on Render
    TEMP_DIR = os.environ.get('TEMP_DIR', '/tmp/ytmp3_temp')
    DOWNLOADS_DIR = os.environ.get('DOWNLOADS_DIR', '/tmp/ytmp3_downloads')

    # Environment variables set in Render dashboard
    SECRET_KEY = os.environ.get('SECRET_KEY')  # Auto-generated by render.yaml
    SECURITY_PASSWORD_SALT = os.environ.get('SECURITY_PASSWORD_SALT')  # Auto-generated by render.yaml
    FFMPEG_PATH = os.environ.get('FFMPEG_PATH', '/usr/bin/ffmpeg')  # Installed via build.sh

class TestingConfig(Config):
    """Testing configuration."""
    DEBUG = True
    TESTING = True
    WTF_CSRF_ENABLED = False
    
    # Use different directories for testing
    TEMP_DIR = os.path.join(Config.BASE_DIR, 'test_temp')
    DOWNLOADS_DIR = os.path.join(Config.BASE_DIR, 'test_downloads')

# Configuration mapping
config = {
    'development': DevelopmentConfig,
    'production': ProductionConfig,
    'testing': TestingConfig,
    'default': DevelopmentConfig
}

def get_config():
    """Get configuration based on environment variable."""
    env = os.environ.get('FLASK_ENV', 'development')
    return config.get(env, DevelopmentConfig)